remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Covert Revolt Campaign Pre-Conditions
description: List of Preconditions that can be unlocked in the Covert Revolt Campaign for Dawn of The Tiberium Age mod for Tiberian Sun
markdown: GFM